export const GET_ALL_COMMENT_API_SAGA = "GET_ALL_COMMENT_API_SAGA";
export const GET_ALL_COMMENT_REDUCER = "GET_ALL_COMMENT_REDUCER";
export const ADD_COMMENT_API_SAGA = "ADD_COMMENT_API_SAGA";
export const DELETE_COMMENT_API_SAGA = "DELETE_COMMENT_API_SAGA";
export const EDIT_COMMENT_API_SAGA = "EDIT_COMMENT_API_SAGA";