export const OPEN_DRAWER = 'OPEN_DRAWER';
export const CLOSE_DRAWER = 'CLOSE_DRAWER';

export const SET_SUBMIT_DRAWER = "SET_SUBMIT_DRAWER"
export const GET_DATA_DRAWER_EDIT_PROJECT = "GET_DATA_DRAWER_EDIT_PROJECT"
export const GET_DATA_DRAWER_EDIT_USER = "GET_DATA_DRAWER_EDIT_USER"