export const CREATE_TASK_API_SAGA = 'CREATE_TASK_API_SAGA';
export const GET_TASK_DETAIL_API_SAGA = 'GET_TASK_DETAIL_API_SAGA';
export const GET_TASK_DETAIL = 'GET_TASK_DETAIL';

export const UPDATE_STATUS_TASK_API_SAGA = 'UPDATE_STATUS_TASK_API_SAGA';
export const UPDATE_CHANGE_TASK_API_SAGA = 'UPDATE_TASK_API_SAGA';
export const HANDLE_DELETE_USER_ASSIGN = 'HANDLE_DELETE_USER_ASSIGN';


export const HANDLE_CHANGE_SELECT_USER_ASSIGN = 'HANDLE_CHANGE_SELECT_USER_ASSIGN';

export const HANDLE_CHANGE_TASK = 'HANDLE_CHANGE_TASK';
